package server

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"strings"
	"time"

	"github.com/Audacity88/eyrie/internal/project"
	"github.com/Audacity88/eyrie/internal/reviewops"
)

func (s *Server) handleCreateReviewTask(w http.ResponseWriter, r *http.Request) {
	var req reviewops.CreateTaskRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": "invalid request body"})
		return
	}
	if _, err := s.projectStore.Get(strings.TrimSpace(req.ProjectID)); err != nil {
		if errors.Is(err, project.ErrNotFound) {
			writeJSON(w, http.StatusNotFound, map[string]string{"error": err.Error()})
			return
		}
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": err.Error()})
		return
	}
	t, err := s.reviewStore.CreateTask(req)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": err.Error()})
		return
	}
	writeJSON(w, http.StatusCreated, t)
}

func (s *Server) handleListReviewTasks(w http.ResponseWriter, r *http.Request) {
	projectID := strings.TrimSpace(r.URL.Query().Get("project_id"))
	tasks, err := s.reviewStore.ListTasks(projectID)
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}
	if tasks == nil {
		tasks = []reviewops.Task{}
	}
	writeJSON(w, http.StatusOK, tasks)
}

func (s *Server) handleGetReviewTask(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	t, err := s.reviewStore.GetTask(id)
	if err != nil {
		if errors.Is(err, reviewops.ErrNotFound) {
			writeJSON(w, http.StatusNotFound, map[string]string{"error": err.Error()})
			return
		}
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}
	writeJSON(w, http.StatusOK, t)
}

func (s *Server) handleRunReviewTask(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	t, err := s.reviewStore.GetTask(id)
	if err != nil {
		if errors.Is(err, reviewops.ErrNotFound) {
			writeJSON(w, http.StatusNotFound, map[string]string{"error": err.Error()})
			return
		}
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}
	if t.Status == reviewops.StatusRunning {
		writeJSON(w, http.StatusConflict, map[string]string{"error": "task already running"})
		return
	}
	if t.Status == reviewops.StatusPosted {
		writeJSON(w, http.StatusConflict, map[string]string{"error": "task already posted"})
		return
	}
	if t.Status == reviewops.StatusFailed {
		writeJSON(w, http.StatusConflict, map[string]string{"error": "task failed; create a new task"})
		return
	}
	if _, err := s.reviewStore.UpdateTaskStatus(id, reviewops.StatusRunning); err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}

	// Delegate to the shared run logic.
	if runErr := s.executeReviewTaskRun(r.Context(), t); runErr != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": runErr.Error()})
		return
	}

	updated, err := s.reviewStore.GetTask(id)
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}
	writeJSON(w, http.StatusOK, updated)
}

// executeReviewTaskRun contains the shared run logic for a review task.
// It fetches source context, builds a TaskResult, persists artifacts,
// and transitions the task to draft_ready or failed.
// The task must already be in running status when this is called.
func (s *Server) executeReviewTaskRun(ctx context.Context, t *reviewops.Task) error {
	id := t.ID

	// Step 1: Attempt to fetch source context if domain is GitHub.
	var fetchErr string
	if t.Domain == reviewops.DomainGitHub {
		var sc *reviewops.SourceContext
		var err error
		switch t.Kind {
		case "triage_issue":
			sc, err = s.githubClient.FetchIssueContext(ctx, t.Repo, t.TargetNumber)
		default:
			sc, err = s.githubClient.FetchPRContext(ctx, t.Repo, t.TargetNumber)
		}
		if err != nil {
			slog.Warn("source context fetch failed", "task", id, "error", err)
			fetchErr = err.Error()
		} else {
			ctxContent := sc.RenderMarkdown()
			if _, err := s.reviewStore.CreateArtifact(reviewops.CreateArtifactRequest{
				TaskID:  id,
				Kind:    reviewops.ArtifactKindSourceContext,
				Content: ctxContent,
			}); err != nil {
				slog.Warn("failed to persist source context artifact", "task", id, "error", err)
				fetchErr = "source context fetched but failed to persist: " + err.Error()
			}
		}
	}

	// Step 2: Build and persist TaskResult JSON artifact.
	draftBody := fmt.Sprintf("# Local stub draft\n\nThis draft was generated by the local deterministic stub runner.\n\n- project_id: `%s`\n- kind: `%s`\n- repo: `%s`\n- target_number: `%d`\n", t.ProjectID, t.Kind, t.Repo, t.TargetNumber)
	if fetchErr != "" {
		draftBody += fmt.Sprintf("\n> **Note**: Source context fetch failed: %s\n", fetchErr)
	}
	draftBody += "\nNo GitHub mutations were performed in this milestone."

	summary := fmt.Sprintf("Stub %s for %s#%d", t.Kind, t.Repo, t.TargetNumber)
	if fetchErr != "" {
		summary += " (source context unavailable)"
	}

	proposedActions := []reviewops.ProposedAction{}
	switch t.Kind {
	case "triage_issue":
		proposedActions = append(proposedActions, reviewops.ProposedAction{
			Kind:        reviewops.ActionPostIssueComment,
			Description: "Post triage analysis as issue comment",
			Body:        draftBody,
		})
	case "review_pr", "rereview_pr":
		proposedActions = append(proposedActions, reviewops.ProposedAction{
			Kind:        reviewops.ActionSubmitPRReview,
			Description: "Submit PR review with draft feedback",
			Body:        draftBody,
		})
	case "respond_reviewer":
		proposedActions = append(proposedActions, reviewops.ProposedAction{
			Kind:        reviewops.ActionPostIssueComment,
			Description: "Post response to reviewer comment",
			Body:        draftBody,
		})
	}

	taskResult := reviewops.TaskResult{
		SchemaVersion:       reviewops.TaskResultSchemaVersion,
		Summary:             summary,
		DraftMarkdown:       draftBody,
		ProposedActions:     proposedActions,
		Confidence:          1.0,
		Severity:            "info",
		Notes:               "Generated by local deterministic stub runner. No LLM or external agent was used.",
		RequiresHumanReview: true,
		GeneratedAt:         time.Now(),
	}

	resultJSON, marshalErr := taskResult.MarshalValidated()
	if marshalErr != nil {
		slog.Warn("failed to marshal task result", "task", id, "error", marshalErr)
	} else {
		if _, err := s.reviewStore.CreateArtifact(reviewops.CreateArtifactRequest{
			TaskID: id, Kind: reviewops.ArtifactKindTaskResult, Content: resultJSON,
		}); err != nil {
			slog.Warn("failed to persist task_result artifact", "task", id, "error", err)
		}
	}

	// Step 3: Create the human-readable markdown draft artifact (always).
	if _, err := s.reviewStore.CreateArtifact(reviewops.CreateArtifactRequest{TaskID: id, Kind: reviewops.ArtifactKindMarkdown, Content: draftBody}); err != nil {
		_, _ = s.reviewStore.UpdateTaskStatus(id, reviewops.StatusFailed)
		return fmt.Errorf("failed to persist draft artifact: %w", err)
	}

	// Step 4: Mark task as draft_ready.
	if _, err := s.reviewStore.UpdateTaskStatus(id, reviewops.StatusDraftReady); err != nil {
		return fmt.Errorf("failed to update task status: %w", err)
	}
	return nil
}

func (s *Server) handleListReviewTaskArtifacts(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	if _, err := s.reviewStore.GetTask(id); err != nil {
		if errors.Is(err, reviewops.ErrNotFound) {
			writeJSON(w, http.StatusNotFound, map[string]string{"error": err.Error()})
			return
		}
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}
	arts, err := s.reviewStore.ListArtifactsByTask(id)
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}
	if arts == nil {
		arts = []reviewops.Artifact{}
	}
	writeJSON(w, http.StatusOK, arts)
}
