package server

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"strings"

	"github.com/Audacity88/eyrie/internal/project"
	"github.com/Audacity88/eyrie/internal/reviewops"
)

func (s *Server) handleCreateReviewTask(w http.ResponseWriter, r *http.Request) {
	var req reviewops.CreateTaskRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": "invalid request body"})
		return
	}
	if _, err := s.projectStore.Get(strings.TrimSpace(req.ProjectID)); err != nil {
		if errors.Is(err, project.ErrNotFound) {
			writeJSON(w, http.StatusNotFound, map[string]string{"error": err.Error()})
			return
		}
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": err.Error()})
		return
	}
	t, err := s.reviewStore.CreateTask(req)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": err.Error()})
		return
	}
	writeJSON(w, http.StatusCreated, t)
}

func (s *Server) handleListReviewTasks(w http.ResponseWriter, r *http.Request) {
	projectID := strings.TrimSpace(r.URL.Query().Get("project_id"))
	tasks, err := s.reviewStore.ListTasks(projectID)
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}
	if tasks == nil {
		tasks = []reviewops.Task{}
	}
	writeJSON(w, http.StatusOK, tasks)
}

func (s *Server) handleGetReviewTask(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	t, err := s.reviewStore.GetTask(id)
	if err != nil {
		if errors.Is(err, reviewops.ErrNotFound) {
			writeJSON(w, http.StatusNotFound, map[string]string{"error": err.Error()})
			return
		}
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}
	writeJSON(w, http.StatusOK, t)
}

func (s *Server) handleRunReviewTask(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	t, err := s.reviewStore.GetTask(id)
	if err != nil {
		if errors.Is(err, reviewops.ErrNotFound) {
			writeJSON(w, http.StatusNotFound, map[string]string{"error": err.Error()})
			return
		}
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}
	if t.Status == reviewops.StatusRunning {
		writeJSON(w, http.StatusConflict, map[string]string{"error": "task already running"})
		return
	}
	if t.Status == reviewops.StatusPosted {
		writeJSON(w, http.StatusConflict, map[string]string{"error": "task already posted"})
		return
	}
	if t.Status == reviewops.StatusFailed {
		writeJSON(w, http.StatusConflict, map[string]string{"error": "task failed; create a new task"})
		return
	}
	if _, err := s.reviewStore.UpdateTaskStatus(id, reviewops.StatusRunning); err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}
	content := fmt.Sprintf("# Local stub draft\n\nThis draft was generated by the local deterministic stub runner.\n\n- project_id: `%s`\n- kind: `%s`\n- repo: `%s`\n- target_number: `%d`\n\nNo GitHub mutations were performed in this milestone.", t.ProjectID, t.Kind, t.Repo, t.TargetNumber)
	if _, err := s.reviewStore.CreateArtifact(reviewops.CreateArtifactRequest{TaskID: id, Kind: reviewops.ArtifactKindMarkdown, Content: content}); err != nil {
		_, _ = s.reviewStore.UpdateTaskStatus(id, reviewops.StatusFailed)
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}
	updated, err := s.reviewStore.UpdateTaskStatus(id, reviewops.StatusDraftReady)
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}
	writeJSON(w, http.StatusOK, updated)
}

func (s *Server) handleListReviewTaskArtifacts(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	if _, err := s.reviewStore.GetTask(id); err != nil {
		if errors.Is(err, reviewops.ErrNotFound) {
			writeJSON(w, http.StatusNotFound, map[string]string{"error": err.Error()})
			return
		}
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}
	arts, err := s.reviewStore.ListArtifactsByTask(id)
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}
	if arts == nil {
		arts = []reviewops.Artifact{}
	}
	writeJSON(w, http.StatusOK, arts)
}
